on: [push, pull_request]
name: CI
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go 1.21
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        check-latest: true
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Test
      run: go test -v -race ./...
    - name: Run go vet
      continue-on-error: true
      run: go vet ./...
